export const Tags = {
  latestPosts: "categories",
  topViewedPosts: "top-viewed-posts",
  categories: "latest-posts",
  layout: "home",
};

const Constants = {
  subHeaders: [
    { label: "Home" },
    { label: "Delhi Election 2025" },
    { label: "Games" },
    { label: "HT Photo Contest" },
    { label: "Long Weekend Planner 2025" },
    { label: "Cricket" },
    { label: "HT Premium" },
    { label: "Horoscope 2025" },
    { label: "India" },
    { label: "World" },
    { label: "Astrology" },
    { label: "Lifestyle" },
    { label: "Education" },
    { label: "Trending" },
    { label: "Business" },
    { label: "Bhopal" },
    { label: "Latest News" },
    { label: "Politics" },
    { label: "Technology" },
    { label: "Bollywood" },
    { label: "Hollywood" },
    { label: "OTT & Web Series" },
    { label: "Health" },
    { label: "Fitness" },
    { label: "Science" },
    { label: "Weather" },
    { label: "Sports" },
    { label: "Football" },
    { label: "Badminton" },
    { label: "Tennis" },
    { label: "Hockey" },
    { label: "Kabbadi" },
    { label: "Wrestling" },
    { label: "Table Tennis" },
    { label: "Athletics" },
    { label: "Motorsports" },
    { label: "Esports" },
    { label: "Auto" },
    { label: "Bike Reviews" },
    { label: "Car Reviews" },
    { label: "Startup & Entrepreneurs" },
    { label: "Stock Market" },
    { label: "Mutual Funds" },
    { label: "Crypto" },
    { label: "Personal Finance" },
    { label: "Banking" },
    { label: "Real Estate" },
    { label: "Travel" },
    { label: "Food" },
    { label: "Recipes" },
    { label: "Fashion" },
    { label: "Beauty" },
    { label: "Wedding" },
    { label: "Relationship" },
    { label: "Parenting" },
    { label: "Spirituality" },
    { label: "Environment" },
    { label: "Wildlife" },
    { label: "Viral" },
    { label: "Social Media Trends" },
    { label: "Gadgets" },
    { label: "Smartphones" },
    { label: "Laptops" },
    { label: "Gaming" },
    { label: "AI & Tech Innovations" },
    { label: "Cybersecurity" },
    { label: "Electric Vehicles" },
    { label: "Indian Railways" },
    { label: "Metro Rail" },
    { label: "Traffic & Roads" },
    { label: "Flights & Aviation" },
    { label: "Civic Issues" },
    { label: "Legal & Courts" },
    { label: "Crime" },
    { label: "Defence & Security" },
    { label: "Opinion & Editorials" },
    { label: "Interviews" },
    { label: "Explainers" },
    { label: "History & Culture" },
    { label: "Festivals of India" },
    { label: "Art & Theatre" },
    { label: "Books & Literature" },
    { label: "Podcasts" },
    { label: "Photography" },
    { label: "Videos" },
    { label: "Web Stories" },
    { label: "Fact Check" },
    { label: "NRI News" },
    { label: "State News" },
    { label: "City News" },
    { label: "Uttar Pradesh" },
    { label: "Maharashtra" },
    { label: "Tamil Nadu" },
    { label: "West Bengal" },
    { label: "Karnataka" },
    { label: "Gujarat" },
    { label: "Punjab" },
    { label: "Bihar" },
    { label: "Madhya Pradesh" },
    { label: "Rajasthan" },
    { label: "Haryana" },
    { label: "Chhattisgarh" },
    { label: "Odisha" },
    { label: "Telangana" },
    { label: "Kerala" },
    { label: "Assam & Northeast" },
  ],
};

export default Constants;
